FROM mcr.microsoft.com/dotnet/sdk:5.0 as build

WORKDIR /src

# copy all files fomr c:/Projekt
COPY . .

RUN dotnet restore

WORKDIR /src/Client

RUN dotnet publish Client.csproj -c release -o /app/Client

FROM mcr.microsoft.com/dotnet/aspnet:5.0 as release

COPY --from=build /app/Client .

EXPOSE 80

ENTRYPOINT ["dotnet","Client.dll"]